### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by cybernet** [Cethy/GooglePlaceAutocompleteBundle#7]
I'm using this bundle with symfony 4.4 this is what i'm getting, no matter what **Type** i'm using
![not_working](https://user-images.githubusercontent.com/125879/69685001-be3b4580-10b2-11ea-91f7-1a21fbdf25a6.png)

**Comment by Cethy** [comment]
Could you provide more details ? Logs ?

**Comment by cybernet** [comment]
my APi key was wrong :)
